title: Best practices for reproducibility and testing
description: Welcome to the main website for the courses: Best practices for reproducibility and testing in scientific software! All the updates will be published here!
google_analytics:
theme: jekyll-theme-cayman
