title: Best practices for reproducibility and testing in scientific software 
description: Welcome to the main website for the courses! All updates will be published here!
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
