title: BSSw courses
description: Welcome to the main website for the courses prepared as a part of the [BSSw fellowship project](https://bssw.io/pages/bssw-fellowship-program)
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
